tests: Fix 2 skipped provideSourceMapFiles tests
Follows-up I60780a255997a in which I renamed file1.js to advanced.js,
which resulted in these two skipped tests.

This also fixes the verifySourceMap.js script which had stopped
working if you use Node 18 or later:

```
Error: You must provide the URL of lib/mappings.wasm by calling
SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
at readWasm (/node_modules/source-map/lib/read-wasm.js:8:13)
```

This was fixed in source-map@0.7.4 per
<https://github.com/mozilla/source-map/issues/432>.

Change-Id: I52140a0cd84a23da5efc7c361b203f850a26cc55